### ISSUE TITLE
Возможно что-то из того, что я считаю ошибками/проблемами, пригодится

### ISSUE THREAD

**Issue by nicothin** [yoksel/bad-practices#1]
http://nicothin.pro/page/oshibki-i-spornye-voprosy-v-html-css-vjorstke
http://nicothin.pro/page/oshibki-i-spornye-voprosy-v-html-css-vjorstke-2
http://nicothin.pro/page/oshibki-i-spornye-voprosy-v-html-css-vjorstke-3

**Comment by yoksel** [comment]
Спасибо : )
Я собираю совсем простые ошибки, которые регулярно совершают студенты в своих учебных проектах. Потом вместо долгих объяснений можно будет просто кинуть ссылку с разбором
