### ISSUE TITLE
Дополнение к разделу "Блоки с текстом"

### ISSUE THREAD

**Issue by grandmaus** [yoksel/bad-practices#3]
Возможно, стоит написать, что для задания высоты кнопок, лучше использовать не `min-height` или `height`, а `padding`, получая таким образом нужную высоту. Так текст будет отцентрирован по вертикали.

**Comment by yoksel** [comment]
Да, надо добавить. Перепишу

**Comment by yoksel** [comment]
Добавила https://yoksel.github.io/bad-practices/blocks-with-text/#fixed-height-right-way

**Comment by grandmaus** [comment]
Супер!
